version: "3.1"

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  frontend:
    build: ../frontend
    stdin_open: true
    tty: true
    volumes:
      - ../frontend/:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    # depends_on:   Add these lines after creating backend service
    #     - backend

volumes:
  node_modules:
