version: "3.5"

services:
  mongo:
    image: mongo:7.0-rc-jammy
    restart: always
    ports:
      - "27017:27017"
    networks:
      - net_backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: virtual-library
    volumes:
      - mongo_data:/data/db

  backend:
    build: ../backend
    networks:
      - net_backend
      - net_frontend
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.host=mongo
    depends_on:
      - mongo

  frontend:
    build: ../frontend
    networks:
      - net_frontend
    stdin_open: true
    tty: true
    volumes:
      - ../frontend/:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend

volumes:
  node_modules:
  mongo_data:

networks:
  net_frontend:
  net_backend: